//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bills
    {
        public int BillID { get; set; }
        public Nullable<int> BillAmount { get; set; }
        public Nullable<int> AccountantsBillID { get; set; }
        public Nullable<int> BillCompany { get; set; }
    
        public virtual InsuranceCompanies InsuranceCompanies { get; set; }
    }
}
