//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumables
    {
        public int ConsumablesID { get; set; }
        public string ConsumablesTitle { get; set; }
        public Nullable<int> ConsumableCount { get; set; }
        public Nullable<int> LaboratorianID { get; set; }
    
        public virtual Laboratorians Laboratorians { get; set; }
    }
}
