//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCompanies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsuranceCompanies()
        {
            this.Bills = new HashSet<Bills>();
        }
    
        public int InsuranceCompanyID { get; set; }
        public string CompanyTitle { get; set; }
        public string Adress { get; set; }
        public string INN { get; set; }
        public string PA { get; set; }
        public string BIC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bills> Bills { get; set; }
    }
}
