//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabEntities : DbContext
    {
        public LabEntities()
            : base("name=LabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accountants> Accountants { get; set; }
        public virtual DbSet<AnalyzerData> AnalyzerData { get; set; }
        public virtual DbSet<Analyzers> Analyzers { get; set; }
        public virtual DbSet<Bills> Bills { get; set; }
        public virtual DbSet<Bio> Bio { get; set; }
        public virtual DbSet<Consumables> Consumables { get; set; }
        public virtual DbSet<InsuranceCompanies> InsuranceCompanies { get; set; }
        public virtual DbSet<Laboratorians> Laboratorians { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<PlicyTypes> PlicyTypes { get; set; }
        public virtual DbSet<RenderedService> RenderedService { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
