//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laboratorians
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Laboratorians()
        {
            this.Consumables = new HashSet<Consumables>();
            this.RenderedService = new HashSet<RenderedService>();
        }
    
        public int LaboratorianID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patron { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
        public Nullable<int> PossibleServices { get; set; }
        public Nullable<int> LaboratorianUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consumables> Consumables { get; set; }
        public virtual Services Services { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RenderedService> RenderedService { get; set; }
    }
}
