//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int LogID { get; set; }
        public Nullable<int> LogUser { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<bool> LogRes { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
