//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Services { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> ServiceStatus { get; set; }
        public Nullable<int> ExecutionTime { get; set; }
    
        public virtual Services Services1 { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
