//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenderedService
    {
        public int RenderedServiceID { get; set; }
        public string RenderedServiceTitle { get; set; }
        public Nullable<System.DateTime> RenderedServiceDate { get; set; }
        public Nullable<int> RenderedServiceWorker { get; set; }
        public Nullable<int> RenderServiceAnalyzer { get; set; }
    
        public virtual AnalyzerData AnalyzerData { get; set; }
        public virtual Analyzers Analyzers { get; set; }
        public virtual Laboratorians Laboratorians { get; set; }
    }
}
